#ifndef DEFS_H
#define DEFS_H

#define SCREEN_WIDTH   800
#define SCREEN_HEIGHT  600
#define CELL_SIZE 20

#define ROWS SCREEN_HEIGHT/CELL_SIZE
#define COLS SCREEN_WIDTH/CELL_SIZE

#define MENU_BUTTONS 2

#endif